function receiveMessageString(n){"use strict";var t={};t.data=n;t.source="";receiveMessage(t)}function receiveMessage(n){"use strict";var r,s,a,h,f,c,v,y,p,w,l;if(localCompartment===null&&(localCompartment=n.source),MSG_TYPE_ADPARAMS===n.data.substr(0,MSG_TYPE_ADPARAMS.length)){if(r=n.data.substr(MSG_TYPE_ADPARAMS.length+1),r!=="")try{adParams=JSON.parse(r)}catch(e){reportAdError("Ad params JSON parse error: "+e.message)}}else if(MSG_TYPE_PRMPARAMS===n.data.substr(0,MSG_TYPE_PRMPARAMS.length)){if(r=n.data.substr(MSG_TYPE_PRMPARAMS.length+1),r!=="")try{prmParams=JSON.parse(r)}catch(e){reportAdError("Prm params JSON parse error: "+e.message)}}else if(MSG_TYPE_APPPARAMS===n.data.substr(0,MSG_TYPE_APPPARAMS.length)){if(r=n.data.substr(MSG_TYPE_APPPARAMS.length+1),r!=="")try{appParams=JSON.parse(r)}catch(e){reportAdError("App options JSON parse error: "+e.message)}}else if(MSG_TYPE_SETID===n.data.substr(0,MSG_TYPE_SETID.length))adControlId=n.data.substr(MSG_TYPE_SETID.length+1);else if(MSG_TYPE_INIT!==n.data.substr(0,MSG_TYPE_INIT.length)&&typeof Ormma!="undefined"&&Ormma!==null){var u=n.data,t=null,i=null,o=u.indexOf(":");o<0?t=u:(t=u.substr(0,o),i=u.substr(o+1));t===MSG_TYPE_SETSIZE?(s=JSON.parse(i),Ormma._setSize(s.width,s.height)):t===MSG_TYPE_SETMAXSIZE?(a=JSON.parse(i),Ormma._maxSize=a):t===MSG_TYPE_SETSCREENSIZE?(h=JSON.parse(i),Ormma._setScreenSize(h.width,h.height)):t===MSG_TYPE_SETSTATE?Ormma._setState(i):t===MSG_TYPE_SETLOCALE?Ormma._setLocale(i):t===MSG_TYPE_SETSDKINFO?(f=JSON.parse(i),Ormma._setSdkVersion(f.sdkVersion,f.client,f.runtimeType)):t===MSG_TYPE_SETCAPABILITY?(c=JSON.parse(i),Ormma._setCapability(c.capability,c.value)):t===MSG_TYPE_SETPLACEMENTTYPE?Ormma._setPlacementType(i):t===MSG_TYPE_START?Ormma._init(i):t===MSG_TYPE_FIRESHAKE?Ormma._shake():t===MSG_TYPE_ORMMA_RESPONSE?Ormma._sendResponse(JSON.parse(i)):t===MSG_TYPE_UPDATETILTCOORDS?(v=JSON.parse(i),Ormma._tiltChange(v)):t===MSG_TYPE_VIEWABLECHANGE?(y=JSON.parse(i),Ormma._viewableChange(y.viewable)):t===MSG_TYPE_UPDATEORIENTATION?(p=JSON.parse(i),Ormma._setOrientation(p.orientation)):t===MSG_TYPE_SETNETWORK?Ormma._setNetwork(i):t===MSG_TYPE_WIREAPPEVENTS?(w=JSON.parse(i),_wireApplicationEvents(w)):t===MSG_TYPE_ERROR?(l=JSON.parse(i),Ormma._throwError(l.action,l.message)):t===MSG_TYPE_SETFOCUS&&i==="true"&&document.body.focus()}}function reportAdError(n){"use strict";console.log(n);postToLocal(MSG_TYPE_ERROR+":"+n)}function postToLocal(n){"use strict";localCompartment!=null&&window.external.notify(n)}function _wireApplicationEvents(n){"use strict";if(n!==null&&typeof n!="undefined"){var t=parseInt(n.events);(t&EVENT_TYPE_ENUM.PointerDown)!=0&&typeof applicationEventHandlers.onPointerDown!="function"?(applicationEventHandlers.onPointerDown=function(t){t.which===2&&n.preventDefault&&t.preventDefault();pointerDown=!0;postToLocal(MSG_TYPE_ONPOINTERDOWN+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,pointerType:t.pointerType,which:t.which}))},window.addEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1)):(t&EVENT_TYPE_ENUM.PointerDown)==0&&typeof applicationEventHandlers.onPointerDown=="function"&&(window.removeEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1),applicationEventHandlers.onPointerDown=null);(t&EVENT_TYPE_ENUM.PointerUp)!=0&&typeof applicationEventHandlers.onPointerUp!="function"?(applicationEventHandlers.onPointerUp=function(n){n.type==="pointerout"?pointerDown&&(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP)):(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP))},window.addEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1)):(t&EVENT_TYPE_ENUM.PointerUp)==0&&typeof applicationEventHandlers.onPointerUp=="function"&&(window.removeEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1),applicationEventHandlers.onPointerUp=null);(t&EVENT_TYPE_ENUM.PointerMove)!=0&&typeof applicationEventHandlers.onPointerMove!="function"?(applicationEventHandlers.onPointerMove=function(n){postToLocal(MSG_TYPE_ONPOINTERMOVE+":"+JSON.stringify({clientX:n.clientX,clientY:n.clientY}))},window.addEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1)):(t&EVENT_TYPE_ENUM.PointerMove)==0&&typeof applicationEventHandlers.onPointerMove=="function"&&(window.removeEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1),applicationEventHandlers.onPointerMove=null);(t&EVENT_TYPE_ENUM.ManipulationStateChanged)!=0&&typeof applicationEventHandlers.onManipulationStateChanged!="function"?(applicationEventHandlers.onManipulationStateChanged=function(n){postToLocal(MSG_TYPE_ONMANIPSTATECHANGED+":"+JSON.stringify({lastState:n.lastState,currentState:n.currentState}))},window.addEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1)):(t&EVENT_TYPE_ENUM.ManipulationStateChanged)==0&&typeof applicationEventHandlers.onManipulationStateChanged=="function"&&(window.removeEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1),applicationEventHandlers.onManipulationStateChanged=null);(t&EVENT_TYPE_ENUM.MouseWheel)!=0&&typeof applicationEventHandlers.onMouseWheel!="function"?(applicationEventHandlers.onMouseWheel=function(t){n.preventDefault&&t.preventDefault();postToLocal(MSG_TYPE_ONMOUSEWHEEL+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,ctrlKey:t.ctrlKey,wheelDelta:t.wheelDelta}))},window.addEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1)):(t&EVENT_TYPE_ENUM.MouseWheel)==0&&typeof applicationEventHandlers.onMouseWheel=="function"&&(window.removeEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1),applicationEventHandlers.onMouseWheel=null)}}window.onerror=function(n,t,i){"use strict";try{console.error("[msg:"+n+"][url:"+t+"][lineNumber:"+i+"]");window.external.notify("error:unhandled ad exception: "+n)}catch(r){}return!0};var localCompartment=null,adControlId=null,pointerDown,adParams=null,prmParams=null,appParams=null,MSG_TYPE_ADPARAMS="adParams",MSG_TYPE_PRMPARAMS="prmParams",MSG_TYPE_APPPARAMS="appParams",MSG_TYPE_INIT="init",MSG_TYPE_SETID="setId",MSG_TYPE_ERROR="error",MSG_TYPE_SETMAXSIZE="setMaxSize",MSG_TYPE_SETSCREENSIZE="setScreenSize",MSG_TYPE_SETSIZE="setSize",MSG_TYPE_SETSTATE="setState",MSG_TYPE_SETPLACEMENTTYPE="setPlacementType",MSG_TYPE_WIREAPPEVENTS="wireAppEvents",MSG_TYPE_START="ormmaStart",MSG_TYPE_ORMMA_RESPONSE="ormmaResponse",MSG_TYPE_FIRESHAKE="fireShake",MSG_TYPE_UPDATETILTCOORDS="updateTiltCoords",MSG_TYPE_UPDATEORIENTATION="updateOrienation",MSG_TYPE_VIEWABLECHANGE="viewableChange",MSG_TYPE_SETNETWORK="setNetwork",MSG_TYPE_SETLOCALE="setLocale",MSG_TYPE_SETSDKINFO="setSdkInfo",MSG_TYPE_SETCAPABILITY="setCapability",MSG_TYPE_SETFOCUS="setFocus",MSG_TYPE_ONPOINTERDOWN="MSPointerDown",MSG_TYPE_ONPOINTERUP="MSPointerUp",MSG_TYPE_ONPOINTERMOVE="MSPointerMove",MSG_TYPE_ONMOUSEWHEEL="MSMouseWheel",MSG_TYPE_ONMANIPSTATECHANGED="MSManipulationStateChanged",EVENT_TYPE_ENUM={All:-1,PointerDown:1,PointerUp:2,PointerMove:4,MouseWheel:16,ManipulationStateChanged:32},applicationEventHandlers={onPointerDown:null,onPointerUp:null,onMouseWheel:null,onPointerMove:null,onManipulationStateChanged:null};
// SIG // Begin signature block
// SIG // MIIdjAYJKoZIhvcNAQcCoIIdfTCCHXkCAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFKpjhl5i8bQd
// SIG // HBrsOnhMdcMSqlmFoIIYajCCBNowggPCoAMCAQICEzMA
// SIG // AADvOz0+YK9JZSAAAAAAAO8wDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE4MDgyMzIw
// SIG // MTk0NFoXDTE5MTEyMzIwMTk0NFowgcoxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVy
// SIG // aWNhIE9wZXJhdGlvbnMxJjAkBgNVBAsTHVRoYWxlcyBU
// SIG // U1MgRVNOOkQyMzYtMzdEQS05NzYxMSUwIwYDVQQDExxN
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIIBIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAygKDPiWV
// SIG // 7dkBwFtH86tQPhKNehsznDsGlNDHfUHEIB+LxQO0eV3n
// SIG // PGNPqx/Pbf4XFhgvcxXPdNEAgImt1WYDO4um0RUS+QNG
// SIG // FDL+he1D1k6qaYq3HGBo1a7O0YibRmz1CmigioYU2dTQ
// SIG // NRQukMLFpsqPmv0dYBbXKB3QjesZ9ETL4eEXCBkiIg6+
// SIG // lZrXVtzdKgw6PP018Q0ta6AoeWzkyBY0pTQBW6mJ6ey/
// SIG // Mz2MHYs1sv1EZu+SPncXzYZ4E4Bo+ysiYZLICJUs5KNF
// SIG // 3SkZ8mhdtjy/NOlGl8pZJSuUg3Uw5NORmgMlfHvrSLDH
// SIG // VUNIcIIdOQRhMRNEdOjR458VKwIDAQABo4IBCTCCAQUw
// SIG // HQYDVR0OBBYEFJQejN4dLTMFA42lACnBfoR/VgEFMB8G
// SIG // A1UdIwQYMBaAFCM0+NlSRnAK7UD7dvuzK7DDNbMPMFQG
// SIG // A1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9jcmwubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY3Jvc29m
// SIG // dFRpbWVTdGFtcFBDQS5jcmwwWAYIKwYBBQUHAQEETDBK
// SIG // MEgGCCsGAQUFBzAChjxodHRwOi8vd3d3Lm1pY3Jvc29m
// SIG // dC5jb20vcGtpL2NlcnRzL01pY3Jvc29mdFRpbWVTdGFt
// SIG // cFBDQS5jcnQwEwYDVR0lBAwwCgYIKwYBBQUHAwgwDQYJ
// SIG // KoZIhvcNAQEFBQADggEBADsr6lmlYEVc7XvEgiY5AeLZ
// SIG // +ix6Fk/mt767TnJJlIAuC5s9HcQkbIsUlZ8+EV8DN2PY
// SIG // t2K8uuUue9Ix21DNgsNmTfWfOsI0sJ+0uFxoBT0ofkNZ
// SIG // dH8qqQ5u6RypPgdZmihHqn0MRVSHKxpmlX0Zv5dDlkqZ
// SIG // csWe9GdhHyup1a7kmxC7P9hzDyYeaXHPsO8ShhlqZyFc
// SIG // GB4+moWnA2yMg+9h6qRah5Eb+Ln1hWwM4KFvtnl1w0ou
// SIG // RIOeD2I180Rk5I93dTBpSyWkYsLH+WR7ctrmZQqJnif2
// SIG // zaAglrsgZsWP9ZplqOoRrxXDqMcY2rg7ouJTiWIYF7nu
// SIG // jlM0px9b3S0wggX/MIID56ADAgECAhMzAAABA14lHJkf
// SIG // ox64AAAAAAEDMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNV
// SIG // BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
// SIG // VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
// SIG // Q29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
// SIG // b2RlIFNpZ25pbmcgUENBIDIwMTEwHhcNMTgwNzEyMjAw
// SIG // ODQ4WhcNMTkwNzI2MjAwODQ4WjB0MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMR4wHAYDVQQDExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
// SIG // AoIBAQDRlHY25oarNv5p+UZ8i4hQy5Bwf7BVqSQdfjnn
// SIG // BZ8PrHuXss5zCvvUmyRcFrU53Rt+M2wR/Dsm85iqXVNr
// SIG // qsPsE7jS789Xf8xly69NLjKxVitONAeJ/mkhvT5E+94S
// SIG // nYW/fHaGfXKxdpth5opkTEbOttU6jHeTd2chnLZaBl5H
// SIG // hvU80QnKDT3NsumhUHjRhIjiATwi/K+WCMxdmcDt66Va
// SIG // mJL1yEBOanOv3uN0etNfRpe84mcod5mswQ4xFo8ADwH+
// SIG // S15UD8rEZT8K46NG2/YsAzoZvmgFFpzmfzS/p4eNZTkm
// SIG // yWPU78XdvSX+/Sj0NIZ5rCrVXzCRO+QUauuxygQjAgMB
// SIG // AAGjggF+MIIBejAfBgNVHSUEGDAWBgorBgEEAYI3TAgB
// SIG // BggrBgEFBQcDAzAdBgNVHQ4EFgQUR77Ay+GmP/1l1jjy
// SIG // A123r3f3QP8wUAYDVR0RBEkwR6RFMEMxKTAnBgNVBAsT
// SIG // IE1pY3Jvc29mdCBPcGVyYXRpb25zIFB1ZXJ0byBSaWNv
// SIG // MRYwFAYDVQQFEw0yMzAwMTIrNDM3OTY1MB8GA1UdIwQY
// SIG // MBaAFEhuZOVQBdOCqhc3NyK1bajKdQKVMFQGA1UdHwRN
// SIG // MEswSaBHoEWGQ2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvY3JsL01pY0NvZFNpZ1BDQTIwMTFfMjAx
// SIG // MS0wNy0wOC5jcmwwYQYIKwYBBQUHAQEEVTBTMFEGCCsG
// SIG // AQUFBzAChkVodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpb3BzL2NlcnRzL01pY0NvZFNpZ1BDQTIwMTFfMjAx
// SIG // MS0wNy0wOC5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG
// SIG // 9w0BAQsFAAOCAgEAn/XJUw0/DSbsokTYDdGfY5YGSz8e
// SIG // XMUzo6TDbK8fwAG662XsnjMQD6esW9S9kGEX5zHnwya0
// SIG // rPUn00iThoj+EjWRZCLRay07qCwVlCnSN5bmNf8MzsgG
// SIG // FhaeJLHiOfluDnjYDBu2KWAndjQkm925l3XLATutghIW
// SIG // IoCJFYS7mFAgsBcmhkmvzn1FFUM0ls+BXBgs1JPyZ6vi
// SIG // c8g9o838Mh5gHOmwGzD7LLsHLpaEk0UoVFzNlv2g24HY
// SIG // tjDKQ7HzSMCyRhxdXnYqWJ/U7vL0+khMtWGLsIxB6aq4
// SIG // nZD0/2pCD7k+6Q7slPyNgLt44yOneFuybR/5WcF9ttE5
// SIG // yXnggxxgCto9sNHtNr9FB+kbNm7lPTsFA6fUpyUSj+Z2
// SIG // oxOzRVpDMYLa2ISuubAfdfX2HX1RETcn6LU1hHH3V6qu
// SIG // +olxyZjSnlpkdr6Mw30VapHxFPTy2TUxuNty+rR1yIib
// SIG // ar+YRcdmstf/zpKQdeTr5obSyBvbJ8BblW9Jb1hdaSre
// SIG // U0v46Mp79mwV+QMZDxGFqk+av6pX3WDG9XEg9FGomsrp
// SIG // 0es0Rz11+iLsVT9qGTlrEOlaP470I3gwsvKmOMs1jaqY
// SIG // WSRAuDpnpAdfoP7YO0kT+wzh7Qttg1DO8H8+4NkI6Iwh
// SIG // SkHC3uuOW+4Dwx1ubuZUNWZncnwa6lL2IsRyP64wggYH
// SIG // MIID76ADAgECAgphFmg0AAAAAAAcMA0GCSqGSIb3DQEB
// SIG // BQUAMF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJ
// SIG // kiaJk/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eTAeFw0wNzA0MDMxMjUzMDlaFw0yMTA0MDMxMzAzMDla
// SIG // MHcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xITAfBgNVBAMTGE1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQTCCASIwDQYJKoZI
// SIG // hvcNAQEBBQADggEPADCCAQoCggEBAJ+hbLHf20iSKnxr
// SIG // LhnhveLjxZlRI1Ctzt0YTiQP7tGn0UytdDAgEesH1VSV
// SIG // FUmUG0KSrphcMCbaAGvoe73siQcP9w4EmPCJzB/LMySH
// SIG // nfL0Zxws/HvniB3q506jocEjU8qN+kXPCdBer9CwQgSi
// SIG // +aZsk2fXKNxGU7CG0OUoRi4nrIZPVVIM5AMs+2qQkDBu
// SIG // h/NZMJ36ftaXs+ghl3740hPzCLdTbVK0RZCfSABKR2YR
// SIG // JylmqJfk0waBSqL5hKcRRxQJgp+E7VV4/gGaHVAIhQAQ
// SIG // MEbtt94jRrvELVSfrx54QTF3zJvfO4OToWECtR0Nsfz3
// SIG // m7IBziJLVP/5BcPCIAsCAwEAAaOCAaswggGnMA8GA1Ud
// SIG // EwEB/wQFMAMBAf8wHQYDVR0OBBYEFCM0+NlSRnAK7UD7
// SIG // dvuzK7DDNbMPMAsGA1UdDwQEAwIBhjAQBgkrBgEEAYI3
// SIG // FQEEAwIBADCBmAYDVR0jBIGQMIGNgBQOrIJgQFYnl+Ul
// SIG // E/wq4QpTlVnkpKFjpGEwXzETMBEGCgmSJomT8ixkARkW
// SIG // A2NvbTEZMBcGCgmSJomT8ixkARkWCW1pY3Jvc29mdDEt
// SIG // MCsGA1UEAxMkTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5ghB5rRahSqClrUxzWPQHEy5lMFAG
// SIG // A1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL21pY3Jvc29m
// SIG // dHJvb3RjZXJ0LmNybDBUBggrBgEFBQcBAQRIMEYwRAYI
// SIG // KwYBBQUHMAKGOGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljcm9zb2Z0Um9vdENlcnQuY3J0
// SIG // MBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEB
// SIG // BQUAA4ICAQAQl4rDXANENt3ptK132855UU0BsS50cVtt
// SIG // DBOrzr57j7gu1BKijG1iuFcCy04gE1CZ3XpA4le7r1ia
// SIG // HOEdAYasu3jyi9DsOwHu4r6PCgXIjUji8FMV3U+rkuTn
// SIG // jWrVgMHmlPIGL4UD6ZEqJCJw+/b85HiZLg33B+JwvBhO
// SIG // nY5rCnKVuKE5nGctxVEO6mJcPxaYiyA/4gcaMvnMMUp2
// SIG // MT0rcgvI6nA9/4UKE9/CCmGO8Ne4F+tOi3/FNSteo7/r
// SIG // vH0LQnvUU3Ih7jDKu3hlXFsBFwoUDtLaFJj1PLlmWLMt
// SIG // L+f5hYbMUVbonXCUbKw5TNT2eb+qGHpiKe+imyk0Bnca
// SIG // Ysk9Hm0fgvALxyy7z0Oz5fnsfbXjpKh0NbhOxXEjEiZ2
// SIG // CzxSjHFaRkMUvLOzsE1nyJ9C/4B5IYCeFTBm6EISXhrI
// SIG // niIh0EPpK+m79EjMLNTYMoBMJipIJF9a6lbvpt6Znco6
// SIG // b72BJ3QGEe52Ib+bgsEnVLaxaj2JoXZhtG6hE6a/qkfw
// SIG // Em/9ijJssv7fUciMI8lmvZ0dhxJkAj0tr1mPuOQh5bWw
// SIG // ymO0eFQF1EEuUKyUsKV4q7OglnUa2ZKHE3UiLzKoCG6g
// SIG // W4wlv6DvhMoh1useT8ma7kng9wFlb4kLfchpyOZu6qeX
// SIG // zjEp/w7FW1zYTRuh2Povnj8uVRZryROj/TCCB3owggVi
// SIG // oAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQELBQAw
// SIG // gYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcwODIx
// SIG // MDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UE
// SIG // AxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAx
// SIG // MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
// SIG // AKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCquAY4
// SIG // GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJDXlk
// SIG // h36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/XllnK
// SIG // YBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPLbfM6
// SIG // XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5pUkp
// SIG // 5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt7UOR
// SIG // g9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3Pv4y
// SIG // 07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwPrRkj
// SIG // hMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDglmDlK
// SIG // Ns98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLEtVc/
// SIG // JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9G9RV
// SIG // S+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/CHFfb
// SIG // g43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kppxMo
// SIG // pqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9AN0/B
// SIG // 4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE2rCI
// SIG // F96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB6TAQ
// SIG // BgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k5VAF
// SIG // 04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAweCgBT
// SIG // AHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQF
// SIG // MAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfH
// SIG // MdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2Ny
// SIG // bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBe
// SIG // BggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCBnwYD
// SIG // VR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYIKwYB
// SIG // BQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggrBgEF
// SIG // BQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABpAGMA
// SIG // eQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkqhkiG
// SIG // 9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuWEeFj
// SIG // kplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79HqaPz
// SIG // adtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS0LD9
// SIG // a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32mkHSD
// SIG // jfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWEljHwlp
// SIG // blqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMOr5ko
// SIG // l5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsatruWy
// SIG // 2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+nt3TD
// SIG // QAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVAKmWj
// SIG // w11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0HjWwec
// SIG // hz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv7Jf2
// SIG // oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3HjXG
// SIG // 0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs6jeZ
// SIG // eRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991bWOR
// SIG // PdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYibV3FW
// SIG // TkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0xggSO
// SIG // MIIEigIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgw
// SIG // JgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBD
// SIG // QSAyMDExAhMzAAABA14lHJkfox64AAAAAAEDMAkGBSsO
// SIG // AwIaBQCggaIwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcC
// SIG // AQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUw
// SIG // IwYJKoZIhvcNAQkEMRYEFPGULQrAoTX2U5VlT2ka11qf
// SIG // tQ8fMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwBy
// SIG // AG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29m
// SIG // dC5jb20wDQYJKoZIhvcNAQEBBQAEggEAYaNXzJhuGZbL
// SIG // ZyIFvGLFHzdFJTPCJSTP8cxVEOAffBgMAot1iuwdOlYf
// SIG // a/AqfRvn8pFpPolrhpztue5CFOAXc8bMlvE5EHac+MZn
// SIG // pd/exmz/AvC70hs/37JKCZVXGJTdETo2E/riM2EEuJbg
// SIG // Y/B3rtFLcXUgyqdTYm3YEc95ZysKqej/in1FfvUFHlJ4
// SIG // BR+C6uqUobKzJios4rfDNWrCINPMZtq3aw8sP0LhsXOg
// SIG // TV3c03ajb+xYTPwkHfP3P0f70+c9so7Dl336mZe9xpso
// SIG // iw50gNEZu/mSNOJBhqBVI8gQO/0IbmSqqL/vF089aZ5B
// SIG // /LHqZFNw6pLHOO2341ZsC6GCAigwggIkBgkqhkiG9w0B
// SIG // CQYxggIVMIICEQIBATCBjjB3MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGltZS1TdGFt
// SIG // cCBQQ0ECEzMAAADvOz0+YK9JZSAAAAAAAO8wCQYFKw4D
// SIG // AhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEw
// SIG // HAYJKoZIhvcNAQkFMQ8XDTE4MTEyMzA0MTAwOVowIwYJ
// SIG // KoZIhvcNAQkEMRYEFBwakoUGQTAoammUXIeluvpyuC6E
// SIG // MA0GCSqGSIb3DQEBBQUABIIBADR6sb+6DjCsSnIEOE3q
// SIG // XyQga3aZFbiqTIeiV9jpnBsIRVJy2W08ItlxOSv5Z6YW
// SIG // gn5ivDS9Ud+mkc5F15fPr6HP8Er+VDCCLkCHCIsFRdsE
// SIG // 130EAdXavt7MqyaNNyhh0Q5BVS+2hy2KRNULdBNJERbu
// SIG // glSy2gAGAem/8Nfn/CekQ0HPI/jh8Zt+AzOKLWt7SHWx
// SIG // /8DVMxLbIh2wovz5z8UpaCRLpPqLXf/djZEvr9wlVdN/
// SIG // hmxMBuuDljgCEpD7rAigLlHqbw4Y/zLCL+in053pCCDM
// SIG // layYpu10IxZaA/iuKQH8ZP3Hs5iSipMjL8dn4sPJroDT
// SIG // DvamJ9I7vbf/JyU=
// SIG // End signature block
